### ISSUE TITLE
Enroller.fromJWT throws "non-null password required"

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti-sdk-jvm#210]
when running using Java 14, trying to initialize a keystore from within code will end up throwing:
```
Exception in thread "main" java.security.KeyStoreException: non-null password required to create PrivateKeyEntry
	at java.base/java.security.KeyStoreSpi.engineSetEntry(KeyStoreSpi.java:558)
	at java.base/sun.security.util.KeyStoreDelegator.engineSetEntry(KeyStoreDelegator.java:173)
	at java.base/java.security.KeyStore.setEntry(KeyStore.java:1584)
	at org.openziti.identity.Enroller.enroll(Enroller.kt:91)
```
This seems to happen due to Enroller.kt where `protect` is initialized to an empty char array or null:
```
        val protect = if (keyStore.type == "PKCS12") KeyStore.PasswordProtection(charArrayOf()) else null

        keyStore.setEntry(alias, pke, protect)
```

**Comment by ekoby** [comment]
fixed in #539 

dup #515
