### ISSUE TITLE
Regression in JVM SDK - 0.23.8+

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti-sdk-jvm#316]
the sample project I generated Aug 2021 no longer works. Using 0.22.+ for my dependency works.
```
  	implementation 'org.openziti:ziti:0.22.+'
```

I'm putting up a PR for the samples in a minute which should illustrate the issue and contains steps to reproduce the issue

**Comment by dovholuknf** [comment]
Manifests in postgres with this log message:
```
postgres-db_1                     | 2022-06-15 21:45:35.787 UTC [34] FATAL:  unsupported frontend protocol 1234.5679: server supports 3.0 to 3.0
```

Regression came after 0.23.7. That version works, after 0.23.7 java fails with:
```
Exception in thread "main" org.postgresql.util.PSQLException: Something unusual has occurred to cause the driver to fail. Please report this exception.
	at org.postgresql.Driver.connect(Driver.java:282)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189)
	at jdbc.postgres.App.main(App.java:37)
Caused by: java.nio.channels.WritePendingException
	at org.openziti.net.ZitiSocketChannel.write(ZitiSocketChannel.kt:365)
	at org.openziti.net.ZitiSocketChannel.write(ZitiSocketChannel.kt:340)
	at java.base/java.nio.channels.AsynchronousSocketChannel.write(AsynchronousSocketChannel.java:582)
	at org.openziti.net.ZitiSocketChannel.write(ZitiSocketChannel.kt:348)
	at org.openziti.net.nio.AsyncSocketImpl$getOutputStream$1.write(AsyncSocketImpl.kt:231)
```

**Comment by ekoby** [comment]
could not reproduce with latest code
