### ISSUE TITLE
After starting the VPN, a NoClassDefFoundError error occurs when the browser accesses the service, causing the program to crash

### ISSUE THREAD

**Issue by alylhb** [openziti/ziti-sdk-jvm#490]
After starting the VPN, a NoClassDefFoundError error occurs when the browser accesses the service, causing the program to crash
The code on line 148 is `val kp = if (service.encryptionRequired) Crypto.newKeyPair() else null`
Here are the error details:
java.lang.NoClassDefFoundError: <clinit> failed for class com.ql.wzwsdk.crypto.Crypto; see exception in other thread
    	at com.ql.wzwsdk.net.ZitiSocketChannel.connectInternal$wzwSdk_debug(ZitiSocketChannel.kt:148)
    	at com.ql.wzwsdk.net.ZitiSocketChannel$connectInternal$1.invokeSuspend(Unknown Source:15)
    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a9c7c6d, Dispatchers.IO]

**Comment by ekoby** [comment]
can you elaborate on the way you use SDK?

is this a fork? Why are the package names different?
