### ISSUE TITLE
HttpClient5 issue creating a connection to a service

### ISSUE THREAD

**Issue by Hazelton42** [openziti/ziti-sdk-jvm#554]
Using the `ziti-springboot-client`'s restTempate to call a service and during the service connection this exception is thrown:
![image](https://github.com/openziti/ziti-sdk-jvm/assets/104400424/63cad6dd-fc2b-40fb-a6e0-ebe4788b8c04)

As you can see from the debug details, the channel is connected but throws an exception when returning the local port.

**Comment by ahazeltonNF** [comment]
Actual exception thrown:
```
java.lang.ClassCastException: class org.openziti.ZitiAddress$Session cannot be cast to class java.net.InetSocketAddress (org.openziti.ZitiAddress$Session is in unnamed module of loader 'app'; java.net.InetSocketAddress is in module java.base of loader 'bootstrap')

    at org.openziti.net.nio.AsyncSocketImpl.getLocalPort(AsyncSocketImpl.kt:87)
    at java.base/java.net.Socket.getLocalPort(Socket.java:913)
    at java.base/java.net.Socket.getLocalSocketAddress(Socket.java:974)
    at org.apache.hc.core5.http.impl.io.BHttpConnectionBase.getEndpointDetails(BHttpConnectionBase.java:344)
```
